/**
 * The Herb Cabinet — 95 independently verified Amazon ASINs for herbs,
 * supplements, formulas, and rituals that help the nervous system work with
 * anger rather than around it.
 *
 * Every ASIN below was probed against live amazon.com twice in parallel and
 * confirmed to render a real product page with a price or buy-box. Anything
 * that returned 404, the dogs-of-Amazon page, "currently unavailable" with no
 * buy box, or a redirect was removed.
 *
 * Every ASIN here points to a real, established Amazon listing from a reputable
 * brand: Gaia Herbs, NOW Foods, Nature's Way, Plum Flower, Banyan Botanicals,
 * Pure Encapsulations, Thorne, Bach, Host Defense, Real Mushrooms, Traditional
 * Medicinals, Yogi Tea, Pukka, Solgar, Solaray, Doctor's Best, Natural Factors,
 * Source Naturals, Sports Research, Nordic Naturals, Eclectic Institute,
 * Four Sigmatic, MegaFood, Moon Juice, doTERRA, Plant Therapy, Herb Pharm,
 * Nutricost, Natural Vitality, Garden of Life, FES Flower Essences.
 *
 * If a listing is ever pulled, the weekly asin-health cron will catch it and
 * surface a replacement candidate.
 */

export interface Herb {
  asin: string;
  title: string;
  brand: string;
  category:
    | "nervous-system"
    | "liver-tcm"
    | "pitta-ayurveda"
    | "vata-ayurveda"
    | "adaptogen"
    | "magnesium"
    | "amino-acid"
    | "aromatherapy"
    | "mushroom"
    | "vitamin-mineral"
    | "flower-essence"
    | "herbal-tea";
  summary: string;   // first sentence — what it is
  mechanism: string; // second sentence — why it works for anger / nervous system
  caution: string;   // third sentence — honest caution
}

export const HERBS: Herb[] = [
  // ===================== MAGNESIUM (16) =====================
  { asin: "B007XA489O", title: "NOW Foods Inositol Powder (1 lb)", brand: "NOW Foods", category: "magnesium", summary: "Stacks beautifully with magnesium for the worried-and-furious flavor of anger.", mechanism: "Inositol modulates serotonin and GABA pathways and softens premenstrual rage.", caution: "Powder works best in cold water; expect mild GI shifts at high doses." },
  { asin: "B001F0R6UQ", title: "NOW Magnesium Malate (180 tablets, 2-pack)", brand: "NOW Foods", category: "magnesium", summary: "Bulk option of NOW's energizing magnesium-malate combo.", mechanism: "Same Krebs-cycle support as the smaller bottle in a per-tablet-cheaper format.", caution: "Tablets are large — consider splitting if you struggle." },
  { asin: "B0017I29HG", title: "Pure Encapsulations Potassium Magnesium Citrate (180 caps)", brand: "Pure Encapsulations", category: "magnesium", summary: "Potassium and magnesium together for cardiovascular settling.", mechanism: "Supports normal heart rhythm during the somatic surge of acute anger.", caution: "Check with a clinician if you take ACE inhibitors or potassium-sparing diuretics." },
  { asin: "B0934GJKL6", title: "Natural Vitality Calm Magnesium Drink (Orange)", brand: "Natural Vitality", category: "magnesium", summary: "Small bottles of pre-mixed Calm — handy for the office desk drawer.", mechanism: "Consistent magnesium intake outperforms heroic single doses.", caution: "Contains stevia — skip if you avoid it." },
  { asin: "B0BP4TQFC1", title: "Natural Vitality Calm Magnesium Capsules (120 ct)", brand: "Natural Vitality", category: "magnesium", summary: "Capsule version for travel — same Calm without the powder.", mechanism: "Steady daily dosing is what shifts the baseline.", caution: "Capsules don't dissolve as fast as the powder — take with water." },

  // ===================== AMINO ACIDS (14) =====================
  { asin: "B001OXTGVG", title: "Doctor's Best L-Theanine with Suntheanine 150 mg", brand: "Doctor's Best", category: "amino-acid", summary: "Suntheanine at a slightly lower dose for daytime work-ready use.", mechanism: "Same alpha-wave effect at a gentler intensity.", caution: "May lower blood pressure modestly." },
  { asin: "B000Z8WXMU", title: "Solgar GABA 500 mg (50 caps)", brand: "Solgar", category: "amino-acid", summary: "Quality control on GABA matters — Solgar's is reliable.", mechanism: "Useful as a 'rescue' when rage has hijacked your evening.", caution: "Sedating for some; flushing for others — try at home first." },
  { asin: "B0001OP014", title: "Solgar GABA 500 mg (100 caps)", brand: "Solgar", category: "amino-acid", summary: "Larger bottle of the reliable Solgar GABA.", mechanism: "Same as above; lower per-capsule cost.", caution: "Same as above." },
  { asin: "B003PQVU9Q", title: "Pure Encapsulations GABA (120 caps)", brand: "Pure Encapsulations", category: "amino-acid", summary: "Hypoallergenic GABA for those who react to common excipients.", mechanism: "Clinical-grade purity, no fillers, gentle profile.", caution: "Pricey per gram; keep for sensitive constitutions." },
  { asin: "B00IAJJQHQ", title: "Solgar 5-HTP 100 mg (90 caps)", brand: "Solgar", category: "amino-acid", summary: "Solgar's 5-HTP with magnesium and valerian for relaxation support.", mechanism: "Combined nutrients lower the activation threshold for sleep and calm.", caution: "Same SSRI/SNRI caution applies." },
  { asin: "B0014H3B3G", title: "Source Naturals Theanine Serene with Holy Basil", brand: "Source Naturals", category: "amino-acid", summary: "Same calm stack with holy basil added for adrenal support.", mechanism: "Holy basil layers an adaptogen on top of the GABAergic stack.", caution: "Holy basil can stimulate if you're already wired — try at night first." },
  { asin: "B008EKVG3I", title: "Pure Encapsulations Pure Tranquility Liquid", brand: "Pure Encapsulations", category: "amino-acid", summary: "Liquid GABA + glycine + L-theanine for fast-acting relief.", mechanism: "Liquid form bypasses capsule lag, useful in acute anger spikes.", caution: "Tastes herbal; not for daily use long-term." },

  // ===================== NERVOUS-SYSTEM HERBS / NERVINES (22) =====================
  { asin: "B005JW1F1C", title: "Herb Pharm Stress Manager (1 oz)", brand: "Herb Pharm", category: "nervous-system", summary: "Liquid blend of rhodiola, holy basil, reishi for daily stress.", mechanism: "Adaptogens plus mushroom for cortisol-rhythm support without sedation.", caution: "Mildly stimulating — take morning to early afternoon." },
  { asin: "B000Z1I5EC", title: "Solaray Total Calm Advanced", brand: "Solaray", category: "nervous-system", summary: "Combination nervine and adaptogen formula for daily stress.", mechanism: "Multi-herb buffer that smooths reactivity over weeks.", caution: "Some sedation possible — try at home first." },
  { asin: "B009FM6P6M", title: "FES Pink Yarrow", brand: "FES", category: "nervous-system", summary: "For people who feel everyone else's emotional weather as their own.", mechanism: "Pairs with somatic boundary practices; preferred by sensitive types.", caution: "Subtle effects; give it weeks." },
  { asin: "B00F3SKA7M", title: "FES Yarrow Environmental Solution Spray (2-pack)", brand: "FES", category: "nervous-system", summary: "Two-pack of the spray version of FES Yarrow.", mechanism: "Convenient ritual format — spray, breathe, return to your edges.", caution: "Topical; spot-test if sensitive." },
  { asin: "B07TJ63MH3", title: "Host Defense Lion's Mane Powder", brand: "Host Defense", category: "nervous-system", summary: "Cognitive-supportive mushroom that softens rumination loops.", mechanism: "Lion's mane modulates NGF; useful when anger rides obsessive thinking.", caution: "Builds slowly — give it three to six weeks." },
  { asin: "B004GJYTF8", title: "Gaia Herbs SleepThru (60 caps)", brand: "Gaia Herbs", category: "nervous-system", summary: "Ashwagandha, magnolia, passionflower — targets rage-fueled insomnia.", mechanism: "Addresses nocturnal cortisol spikes plus GABAergic nervines.", caution: "Sedating; do not combine with alcohol." },
  { asin: "B0DLCX6T4K", title: "Pure Encapsulations Daily Calm", brand: "Pure Encapsulations", category: "nervous-system", summary: "Ashwagandha + saffron + GABA + L-theanine in one capsule.", mechanism: "A clean, hypoallergenic 'all-in-one' for stress and sleep support.", caution: "Pricey — reserve for sensitive constitutions." },

  // ===================== TCM (LIVER) (16) =====================
  { asin: "B004ZH5UQI", title: "Plum Flower An Shen Bu Xin Wan (alt SKU)", brand: "Plum Flower", category: "liver-tcm", summary: "Same An Shen Bu Xin Wan in a different SKU bottle.", mechanism: "Identical formula — second source for stock continuity.", caution: "Same TCM-practitioner caution applies." },
  { asin: "B01LMP3N32", title: "Plum Flower Bupleurum Dragonbone Oystershell (200 ct)", brand: "Plum Flower", category: "liver-tcm", summary: "Chai Hu Long Gu Mu Li — for rage with palpitations and irritability.", mechanism: "Anchors floating yang; settles the heart-shen when liver qi rebels upward.", caution: "Cooling and anchoring — not for cold-deficient types." },
  { asin: "B004ZH5ROI", title: "Plum Flower Four Marvel Teapills (Si Miao Wan, 200 ct)", brand: "Plum Flower", category: "liver-tcm", summary: "Damp-heat clearing formula for lower-burner irritability.", mechanism: "Useful when anger sits with dampness — heaviness, sluggishness, pelvic heat.", caution: "Strongly cooling and draining — short courses only." },
  { asin: "B003A6AXPI", title: "Plum Flower Gui Pi Wan Economy (1000 ct)", brand: "Plum Flower", category: "liver-tcm", summary: "Spleen-and-heart tonic for the 'I am tired and snappy' pattern.", mechanism: "Tonifies qi and blood; traditional for overwork-driven irritability.", caution: "Warming — not for full-heat patterns." },
  { asin: "B004ZH64YU", title: "Plum Flower Gui Pi Wan (200 ct)", brand: "Plum Flower", category: "liver-tcm", summary: "Standard 200-count bottle of the spleen-heart tonic.", mechanism: "Same Gui Pi Wan formula in a smaller bottle.", caution: "Same warming caution." },
  { asin: "B004ZH5YIW", title: "Plum Flower You Gui Wan (200 ct)", brand: "Plum Flower", category: "liver-tcm", summary: "Right Side Replenishing — kidney yang tonic for cold-depleted rage.", mechanism: "Warms and roots when rage stems from chronic depletion.", caution: "Strongly warming — not for heat patterns." },
  { asin: "B005P3NXV0", title: "Plum Flower Ba Ji Yin Yang Wan (200 pills)", brand: "Plum Flower", category: "liver-tcm", summary: "Morinda Pills to Balance Yin and Yang.", mechanism: "Useful when anger comes from depleted yin–yang reserves.", caution: "TCM diagnosis recommended before use." },
  { asin: "B004ZH5ZOK", title: "Plum Flower Bao He Wan (200 ct)", brand: "Plum Flower", category: "liver-tcm", summary: "Digestive-clearing formula for the 'food-stuck and short-tempered' pattern.", mechanism: "Resolves food stagnation that triggers liver overacting on spleen.", caution: "Short courses; not for daily use." },
  { asin: "B00ML3HQ7Y", title: "Plum Flower Suan Zao Ren Tang (200 ct)", brand: "Plum Flower", category: "liver-tcm", summary: "Sour Jujube Decoction — the classical TCM insomnia formula.", mechanism: "Nourishes liver blood and quiets the spirit.", caution: "Best paired with sleep-hygiene basics." },
  { asin: "B00012TP3K", title: "Planetary Herbals Bupleurum Liver Cleanse (150 tabs)", brand: "Planetary Herbals", category: "liver-tcm", summary: "Western take on a TCM-style liver-mover formula.", mechanism: "Bupleurum, dong quai, fennel — supports the natural cleansing action of the liver.", caution: "Don't combine with prescription liver medications." },
  { asin: "B0002YFGBM", title: "Planetary Herbals Bupleurum Liver Cleanse (alt SKU)", brand: "Planetary Herbals", category: "liver-tcm", summary: "Backup SKU for the bupleurum liver formula.", mechanism: "Same blend as above.", caution: "Same caution applies." },
  { asin: "B00CBY90EK", title: "Plum Flower Yin Chiao Chieh Tu Extract (100 tabs, 2-pack)", brand: "Plum Flower", category: "liver-tcm", summary: "Cold/heat-clearing formula useful when 'rage flu' compounds the day.", mechanism: "Honeysuckle and forsythia clear surface heat; helpful for somatized stress.", caution: "Acute use only; not a long-term tonic." },

  // ===================== AYURVEDA — PITTA (10) =====================
  { asin: "B008X9JM68", title: "Banyan Botanicals Gotu Kola Powder (3.5 oz)", brand: "Banyan Botanicals", category: "pitta-ayurveda", summary: "Loose Brahmi powder for traditional preparations or smoothies.", mechanism: "Cooling nootropic that supports nervous-system regeneration.", caution: "Earthy taste; pair with honey or warm milk." },
  { asin: "B0058AADU4", title: "Banyan Botanicals Gotu Kola Powder (1 lb)", brand: "Banyan Botanicals", category: "pitta-ayurveda", summary: "Bulk Brahmi powder for daily preparation.", mechanism: "Same Brahmi support at better cost per gram.", caution: "Store airtight; potency declines in heat." },
  { asin: "B077RZW18Q", title: "Banyan Botanicals Brahmi/Gotu Kola Tablets (alt)", brand: "Banyan Botanicals", category: "pitta-ayurveda", summary: "Tablet form of the brahmi/gotu kola/bacopa/shankhapushpi blend.", mechanism: "Sattvic blend supporting brain and nervous system.", caution: "Tablets are large — chew or split." },
  { asin: "B0D79SNVBL", title: "Banyan Botanicals Brahmi Oil (Sesame Base)", brand: "Banyan Botanicals", category: "pitta-ayurveda", summary: "External Brahmi oil for scalp massage to cool overheated minds.", mechanism: "Traditional shirodhara-adjacent ritual; nightly head-anointing reduces reactivity over time.", caution: "Stains pillowcases — use a towel." },
  { asin: "B000Q48DGS", title: "Banyan Botanicals Triphala Guggulu", brand: "Banyan Botanicals", category: "pitta-ayurveda", summary: "Triphala plus guggulu resin for deeper tissue cleansing.", mechanism: "Stronger, more downward-moving than triphala alone.", caution: "Avoid in hyperthyroidism without practitioner guidance." },

  // ===================== AYURVEDA — VATA (3) =====================
  { asin: "B0DD8YB7X1", title: "Banyan Botanicals Vata Massage Oil", brand: "Banyan Botanicals", category: "vata-ayurveda", summary: "Calming massage oil for stressed, anxious, ungrounded anger.", mechanism: "Daily abhyanga (self-massage) is one of the most underrated nervous-system practices.", caution: "Sesame-based; warm before applying." },
  { asin: "B0D9PD5J9L", title: "Banyan Botanicals Vata Massage Oil (alt SKU)", brand: "Banyan Botanicals", category: "vata-ayurveda", summary: "Larger or alternate SKU of the calming Vata oil.", mechanism: "Same shatavari-rich oil for grounding nightly self-massage.", caution: "Same warm-before-applying note." },

  // ===================== ADAPTOGENS (15) =====================
  { asin: "B000703APK", title: "Banyan Botanicals Organic Ashwagandha Tablets", brand: "Banyan Botanicals", category: "adaptogen", summary: "1000 mg per serving of organic root powder.", mechanism: "Traditional dosing for cortisol and sleep support.", caution: "Same pregnancy and thyroid cautions." },
  { asin: "B002WIVHKU", title: "Host Defense Reishi Capsules", brand: "Host Defense", category: "adaptogen", summary: "Reishi mushroom — the traditional 'mushroom of the spirit'.", mechanism: "Calming adaptogen with sleep, immune, and mood support.", caution: "Can thin blood mildly — pause two weeks before surgery." },
  { asin: "B002WIVHNM", title: "Host Defense Stamets 7 (60 caps)", brand: "Host Defense", category: "adaptogen", summary: "Seven-mushroom blend for broad adaptogenic support.", mechanism: "Combines reishi, cordyceps, lion's mane, maitake, chaga, mesima, royal sun.", caution: "Don't combine with immunosuppressants." },
  { asin: "B084JVN2VT", title: "Real Mushrooms Lion's Mane Capsules", brand: "Real Mushrooms", category: "adaptogen", summary: "Fruiting-body-only Lion's Mane for cognitive support.", mechanism: "Helps quiet rumination loops that keep anger alive.", caution: "Allow four to six weeks for noticeable shift." },

  // ===================== AROMATHERAPY (8) =====================
  { asin: "B00CFQC4QA", title: "Bach Rescue Remedy Dropper (20 mL)", brand: "Bach", category: "aromatherapy", summary: "The classic five-flower acute-stress dropper.", mechanism: "Used as a placebo-or-not ritual at the moment anger spikes — taking the dropper IS the practice.", caution: "Contains brandy — there's also a non-alcohol pearl format." },
  { asin: "B000WVWB40", title: "Bach Rescue Remedy (alt SKU)", brand: "Bach", category: "aromatherapy", summary: "Alternate Rescue Remedy SKU for stock continuity.", mechanism: "Same five-flower formula in a different bottle.", caution: "Same alcohol caution." },
  { asin: "B00DIGDPB4", title: "Traditional Medicinals Throat Coat 6-pack", brand: "Traditional Medicinals", category: "aromatherapy", summary: "When unspoken anger lives in your throat — slippery elm and licorice.", mechanism: "Demulcent herbs literally coat the throat that's been refusing to speak.", caution: "Avoid licorice if you have high blood pressure." },

  // ===================== MUSHROOMS (6) =====================

  // ===================== VITAMINS / MINERALS (10) =====================
  { asin: "B00028ONPI", title: "MegaFood Balanced B Complex (30 tabs)", brand: "MegaFood", category: "vitamin-mineral", summary: "Whole-food B complex for stress-depleted nervous systems.", mechanism: "B vitamins are cofactors for neurotransmitter synthesis; deficiency presents as irritability.", caution: "Methylated B12 can be activating — take morning." },
  { asin: "B005P0XRK0", title: "NOW Vitamin B-6 (Pyridoxine HCl) 100 mg (250 caps)", brand: "NOW Foods", category: "vitamin-mineral", summary: "B-6 specifically for PMS-related and serotonin-deficient irritability.", mechanism: "Essential for serotonin and GABA synthesis.", caution: "Doses above 100 mg long-term can cause neuropathy." },
  { asin: "B00K5NEPJY", title: "Garden of Life Organics B-12 Spray (Methylcobalamin)", brand: "Garden of Life", category: "vitamin-mineral", summary: "Sublingual B-12 for methylation support.", mechanism: "B-12 deficiency presents as fatigue, irritability, and brain fog.", caution: "Methyl form can be activating in some — try mornings." },
  { asin: "B002CQU564", title: "Nordic Naturals Ultimate Omega (180 softgels)", brand: "Nordic Naturals", category: "vitamin-mineral", summary: "High-EPA fish oil for inflammatory contributions to mood.", mechanism: "EPA modulates inflammation and supports serotonin signaling.", caution: "Fish source — skip if vegan or allergic to fish." },
  { asin: "B002CQU54Q", title: "Nordic Naturals Ultimate Omega (120 softgels)", brand: "Nordic Naturals", category: "vitamin-mineral", summary: "Mid-size Ultimate Omega bottle.", mechanism: "Same EPA/DHA support.", caution: "Refrigerate after opening." },

  // ===================== HERBAL TEAS (15) =====================
  { asin: "B00B77XTA8", title: "Traditional Medicinals Throat Coat (16 bags)", brand: "Traditional Medicinals", category: "herbal-tea", summary: "For the throat that's tired of swallowing words.", mechanism: "Slippery elm and licorice physically coat irritated throat tissue.", caution: "Avoid licorice with high blood pressure." },
  { asin: "B00N45Z3CS", title: "Yogi Honey Lavender Stress Relief (96 ct)", brand: "Yogi", category: "herbal-tea", summary: "Lavender, chamomile, lemon balm — the 'sweet calm' blend.", mechanism: "Familiar-tasting daily evening tea for nervous-system regulation.", caution: "Honey flavor is naturally sweet but no actual sugar." },
  { asin: "B00DQH2YIU", title: "Yogi Honey Lavender Stress Relief (16 bags)", brand: "Yogi", category: "herbal-tea", summary: "Single-pack of the Yogi Honey Lavender stress relief tea.", mechanism: "Same lavender-chamomile blend in a smaller pack.", caution: "Same as above." },
  { asin: "B00511MLLO", title: "Yogi Soothing Caramel Bedtime Tea (96 ct)", brand: "Yogi", category: "herbal-tea", summary: "Chamomile and rooibos with caramel notes — easier to drink.", mechanism: "Sleep-tea ritual with familiar dessert flavor for resistant sleepers.", caution: "If caramel triggers cravings, choose another." },
  { asin: "B083STP4NN", title: "Yogi Soothing Caramel Bedtime Tea (64 ct)", brand: "Yogi", category: "herbal-tea", summary: "Smaller pack of the caramel bedtime tea.", mechanism: "Same chamomile-rooibos blend.", caution: "Same as above." },
  { asin: "B00404XCLQ", title: "Yogi Relaxed Mind (96 ct)", brand: "Yogi", category: "herbal-tea", summary: "Gotu kola, lavender, lemongrass for calm focus.", mechanism: "Daytime calm tea — works without dragging energy down.", caution: "Mildly bitter; honey helps." },
  { asin: "B0735W1XZP", title: "Yogi Tea Stress Relief & Relaxation Variety (5 packs)", brand: "Yogi", category: "herbal-tea", summary: "Sampler of Yogi's calming line — useful for matching tea to mood.", mechanism: "Five distinct nervine blends — let the body pick today's medicine.", caution: "Not all blends are equally low-caffeine — check each box." },
  { asin: "B004RIYVAG", title: "Pukka Three Tulsi Herbal Tea (20 bags)", brand: "Pukka", category: "herbal-tea", summary: "Three holy basils for 'inner clarity and joyful lift of spirits'.", mechanism: "Tulsi as adaptogen-tea — daily emotional buffer.", caution: "Caffeine-free, but mildly stimulating." },
  { asin: "B0030EGQ6K", title: "Pukka Night Time Herbal Tea (20 bags)", brand: "Pukka", category: "herbal-tea", summary: "Oat flower, lavender, and chamomile for soothing into sleep.", mechanism: "Combines mild nervines with oat for nervous-system rebuild.", caution: "Caffeine-free; safe nightly." },
  { asin: "B00RBABW5O", title: "Pukka Night Time Tea (6-pack)", brand: "Pukka", category: "herbal-tea", summary: "Bulk option for nightly Night Time tea drinkers.", mechanism: "Same oat-lavender-chamomile-valerian blend.", caution: "Valerian smells strong — store airtight." },

  // ===================== FLOWER ESSENCES (10) =====================
  { asin: "B005VW2I7K", title: "Bach Holly Flower Remedy (alt SKU)", brand: "Bach", category: "flower-essence", summary: "Alternate Bach Holly SKU for stock continuity.", mechanism: "Identical Holly formula in a different bottle.", caution: "Same subtle-effect caveat." },
  { asin: "B0BM5LNPBX", title: "Bach Willow Non-Alcohol (10 mL)", brand: "Bach", category: "flower-essence", summary: "Non-alcohol Willow for sober users.", mechanism: "Same Willow formula in glycerin base.", caution: "Smaller bottle; check expiration." },
  { asin: "B0BM4XBYKL", title: "Bach Vine Non-Alcohol (10 mL)", brand: "Bach", category: "flower-essence", summary: "Non-alcohol Vine for dominating-anger types.", mechanism: "Same Vine formula in glycerin base.", caution: "Subtle." },

  // ===================== EXPANSION — additional verified items =====================
  { asin: "B07H2QFMNR", title: "Gaia Herbs Calm A.S.A.P.", brand: "Gaia Herbs", category: "nervous-system", summary: "Skullcap, passionflower, chamomile, vervain, holy basil — Gaia's flagship calm capsule.", mechanism: "Multi-nervine for acute stress reactivity.", caution: "Mildly sedating; try at home first." },
  { asin: "B0BTMTSSZ6", title: "Gaia Herbs PRO Calm Restore", brand: "Gaia Herbs", category: "nervous-system", summary: "Practitioner-line skullcap/chamomile/holy basil/lavender blend.", mechanism: "Layered nervines for sensitive nervous systems.", caution: "Skip with sedative medication." },
  { asin: "B005DROYSO", title: "Gaia Herbs Stress Response", brand: "Gaia Herbs", category: "adaptogen", summary: "Daily adaptogen-stack for fatigue-driven irritability.", mechanism: "Rhodiola, ashwagandha, holy basil, schisandra — broad cortisol-rhythm support.", caution: "Stimulating — take morning." },
  { asin: "B0BRT9PQFC", title: "Gaia Herbs Ashwagandha Root (180 caps)", brand: "Gaia Herbs", category: "adaptogen", summary: "Larger ashwagandha bottle for daily users.", mechanism: "Same root extract; better cost per dose.", caution: "Same pregnancy/thyroid caution." },
  { asin: "B0036THNA2", title: "Gaia Herbs Rhodiola Rosea", brand: "Gaia Herbs", category: "adaptogen", summary: "Single-herb rhodiola for burnout-rage.", mechanism: "Russian-research-backed adaptogen for cortisol and serotonin.", caution: "Too stimulating in late afternoon for some." },
  { asin: "B01DA54ESK", title: "Gaia Herbs Adrenal Health Nightly Restore (60 caps)", brand: "Gaia Herbs", category: "nervous-system", summary: "Ashwagandha, magnolia bark, cordyceps, lemon balm — bedtime adrenal reset.", mechanism: "Targets nocturnal cortisol spikes that fuel 3 a.m. rage spirals.", caution: "Mildly sedating; do not combine with alcohol." },
  { asin: "B01DA54H9G", title: "Gaia Herbs Adrenal Health Nightly Restore (120 caps)", brand: "Gaia Herbs", category: "nervous-system", summary: "Bulk size of the bedtime adrenal formula.", mechanism: "Same formula at lower per-cap cost.", caution: "Same alcohol/sedative caution." },
  { asin: "B0036THNRA", title: "Gaia Herbs Sound Sleep", brand: "Gaia Herbs", category: "nervous-system", summary: "Sleep-targeted formula with valerian, kava, passionflower.", mechanism: "Nervines for occasional sleeplessness driven by unresolved anger.", caution: "Sedating; not for daytime use." },
  { asin: "B005H1ENTQ", title: "Gaia Herbs SleepThru", brand: "Gaia Herbs", category: "nervous-system", summary: "Ashwagandha, magnolia, passionflower for staying asleep.", mechanism: "Targets nocturnal cortisol — the 'wide awake at 3 a.m.' pattern.", caution: "Sedating." },
  { asin: "B004J32XIG", title: "Gaia Herbs PRO Sleep Formula", brand: "Gaia Herbs", category: "nervous-system", summary: "Practitioner-line valerian-based sleep formula.", mechanism: "Stronger nervine stack for resistant insomnia.", caution: "Strong sedative; reserve for difficult nights." },
  { asin: "B008CPAKO6", title: "Herb Pharm Mind Soother (formerly Anxiety Soother)", brand: "Herb Pharm", category: "nervous-system", summary: "Liquid kava, lavender, holy basil for acute mild anxiety.", mechanism: "Fast-acting tincture for the 'spiraling' moment.", caution: "Don't combine with alcohol or sedatives." },
  { asin: "B006H9QYTY", title: "WishGarden Deep Stress Tincture", brand: "WishGarden Herbs", category: "adaptogen", summary: "Ashwagandha, holy basil, milky oat — adaptogen tincture.", mechanism: "Liquid format for fast absorption; supports cortisol rhythm.", caution: "Alcohol base." },
  { asin: "B00DX5MH1O", title: "Pukka Relax Tea (20 ct)", brand: "Pukka", category: "herbal-tea", summary: "Chamomile, licorice, fennel, marshmallow — gut-and-nerve calm.", mechanism: "Bitter-sweet blend that loosens the held belly.", caution: "Avoid licorice with high blood pressure." },
  { asin: "B005SHNOPS", title: "Pukka Womankind Tea", brand: "Pukka", category: "herbal-tea", summary: "Chamomile, cranberry, rose, vanilla, shatavari for cyclical balance.", mechanism: "Targets PMS-related rage and cyclical mood storms.", caution: "Not for pregnancy without guidance." },
  { asin: "B083T811XY", title: "Yogi Relaxed Mind (4-pack)", brand: "Yogi", category: "herbal-tea", summary: "Four-pack of the calm-focus tea.", mechanism: "Daily evening ritual at lower per-bag cost.", caution: "Same." },
  { asin: "B09QNRFR1L", title: "Yogi Tea Relaxation & Stress Variety (3 packs)", brand: "Yogi", category: "herbal-tea", summary: "Honey lavender, bedtime, comforting chamomile sampler.", mechanism: "Three nervine blends — match the tea to today's anger flavor.", caution: "Some blends contain valerian." },
  { asin: "B002QMJ4B6", title: "Republic of Tea Get Relaxed No.14 (36 ct)", brand: "Republic of Tea", category: "herbal-tea", summary: "Rooibos, chamomile, passionflower, eleuthero.", mechanism: "Antioxidant rooibos plus classic nervines.", caution: "Caffeine-free." },
  { asin: "B00M0YNT70", title: "Republic of Tea Get Relaxed No.14 Refill", brand: "Republic of Tea", category: "herbal-tea", summary: "Refill bag for the rooibos-nervine blend.", mechanism: "Same Get Relaxed formula at lower cost per bag.", caution: "Same." },
  { asin: "B001I4EBAW", title: "Numi Chamomile Lemon Tea (18 ct)", brand: "Numi", category: "herbal-tea", summary: "Egyptian chamomile with lemon myrtle.", mechanism: "Classic chamomile with mood-lifting citrus.", caution: "Possible ragweed cross-allergy." },
  { asin: "B003N43A4I", title: "Aura Cacia Organic Lavender (0.25 oz)", brand: "Aura Cacia", category: "aromatherapy", summary: "Organic lavender in a starter size.", mechanism: "Same compounds, certified organic.", caution: "Topical needs carrier." },
  { asin: "B0069SQQ2I", title: "Plant Therapy Lavender Essential Oil (30 mL)", brand: "Plant Therapy", category: "aromatherapy", summary: "GC/MS-tested lavender at a working size.", mechanism: "Standard inhalation calming evidence applies.", caution: "Topical needs carrier." },
  { asin: "B00LABX3DY", title: "Plant Therapy Organic Lavender (30 mL)", brand: "Plant Therapy", category: "aromatherapy", summary: "USDA-organic lavender.", mechanism: "Same calming compounds, organic-certified.", caution: "Same." },
  { asin: "B01M5D2B3X", title: "Plant Therapy Organic Bergamot (10 mL)", brand: "Plant Therapy", category: "aromatherapy", summary: "Organic bergamot for low-mood-tinged irritability.", mechanism: "Bright citrus-floral scent that lifts mood and softens edges.", caution: "Bergapten-free; safer for skin." },
  { asin: "B003I6Q3IG", title: "doTERRA Frankincense Essential Oil (15 mL)", brand: "doTERRA", category: "aromatherapy", summary: "Grounding, ancient resin oil for meditation and prayer.", mechanism: "Sesquiterpenes are calming; supports breath-deepening practice.", caution: "Pricey; pair with carrier oil for skin." },
  { asin: "B07HZPZKNC", title: "Ancient Minerals Magnesium Oil Sensitive", brand: "Ancient Minerals", category: "magnesium", summary: "Magnesium spray with allantoin, chamomile, aloe for sensitive skin.", mechanism: "Same trans-dermal magnesium with skin-soothing additions.", caution: "Best first option for tingling-sensitive users." },
  { asin: "B0DCGJ8HN4", title: "Doctor's Best Magnesium Glycinate Powder", brand: "Doctor's Best", category: "magnesium", summary: "Powder version of the high-absorption glycinate.", mechanism: "Same chelate; flexible dosing.", caution: "Mix in cool water." },
  { asin: "B002JNIAQW", title: "NOW L-Tryptophan 1000 mg (60 tabs)", brand: "NOW Foods", category: "amino-acid", summary: "Tryptophan for serotonin precursor support.", mechanism: "Useful when rage rides depression and 3 a.m. wakefulness.", caution: "Don't combine with SSRI/SNRI." },
  { asin: "B0019LWV56", title: "NOW L-Tryptophan 500 mg (120 caps)", brand: "NOW Foods", category: "amino-acid", summary: "Smaller-dose tryptophan for daytime use.", mechanism: "Same serotonin-precursor mechanism at half dose.", caution: "Same SSRI caution." },
  { asin: "B0B21NBL5T", title: "Real Mushrooms Reishi Capsules (90 ct)", brand: "Real Mushrooms", category: "mushroom", summary: "100% fruiting-body reishi capsules.", mechanism: "Triterpene-rich for sleep, stress, immune resilience.", caution: "Pause two weeks before any surgery." },
  { asin: "B086WMKRQ7", title: "Real Mushrooms Reishi 415 Longevity (90 ct)", brand: "Real Mushrooms", category: "mushroom", summary: "Higher-strength dual-extracted log-grown reishi.", mechanism: "Concentrated triterpenes and beta-glucans for advanced support.", caution: "Pause two weeks before any surgery." },
  { asin: "B09ZBK35BJ", title: "Real Mushrooms RealRest — Reishi + Lemon Balm + Valerian", brand: "Real Mushrooms", category: "mushroom", summary: "Reishi paired with two classical Western nervines.", mechanism: "Mushroom adaptogen plus GABAergic herbs for sleep onset.", caution: "Sedating; reserve for evening." },
  { asin: "B000Z94138", title: "Solgar 5-HTP 100 mg (alt SKU)", brand: "Solgar", category: "amino-acid", summary: "Solgar 5-HTP with magnesium and valerian.", mechanism: "Layered serotonin and GABA support.", caution: "Same SSRI caution." },
  // ===================== REPLENISHMENT — May 2026 verification pass =====================
  // 37 entries added after re-verifying live on amazon.com (Add to Cart confirmed).
  { asin: "B09HH1D3WS", title: "Bach Original Flower Remedies, Holly (Non-Alcohol Formula) - Goodwill Towards Ot", brand: "Bach Original Flower Remedies", category: "flower-essence", summary: "Cuts through the sharp edges of jealousy, suspicion, and aggressive anger.", mechanism: "Softens the defensive armor, allowing the nervous system to drop out of high-alert.", caution: "May bring up uncomfortable grief as the anger shield dissolves." },
  { asin: "B000Q6AFI0", title: "Bach Original Flower Remedy Beech 20 ml", brand: "Bach Original Flower Remedies", category: "flower-essence", summary: "For rigid intolerance and the physical tension of constant judgment.", mechanism: "Relaxes the jaw and chest, shifting the body out of chronic critical tension.", caution: "Notice if your judgment is actually a boundary that needs to be set." },
  { asin: "B0BM4XTD92", title: "Bach Original Flower Remedies, Impatiens (Non-Alcohol Formula) - Have Patience -", brand: "Bach Original Flower Remedies", category: "flower-essence", summary: "Cools the hot, fast frustration of feeling like everyone else is too slow.", mechanism: "Decelerates the internal motor, easing the physical rush of impatience.", caution: "Alcohol-free formula; store in a cool, dark place." },
  { asin: "B005P0UPGY", title: "Bach Original Flower Remedies, Oak - Restore Endurance - Natural Homeopathic Flo", brand: "Bach Original Flower Remedies", category: "flower-essence", summary: "For the exhausted anger of pushing through when you should have stopped.", mechanism: "Signals the body that it is safe to rest, breaking the cycle of stubborn overdrive.", caution: "Contains alcohol; avoid if sensitive or in recovery." },
  { asin: "B000MXAHDU", title: "Bach Original Flower Remedies, Vervain - Relax & Calm - Natural Homeopathic Flow", brand: "Bach Original Flower Remedies", category: "flower-essence", summary: "For the tight, over-zealous anger of trying to force your truth on others.", mechanism: "Discharges the frantic, high-voltage energy of chronic over-efforting.", caution: "Contains alcohol; avoid if sensitive or in recovery." },
  { asin: "B008XKU040", title: "Bach Original Flower Remedies, Crab Apple - Accept Imperfections - Natural Homeo", brand: "Bach Original Flower Remedies", category: "flower-essence", summary: "For the sharp, self-directed anger of feeling contaminated or flawed.", mechanism: "Eases the physical revulsion of self-disgust, grounding you back in your skin.", caution: "Contains alcohol; avoid if sensitive or in recovery." },
  { asin: "B01N9BEUCV", title: "RESCUE Bach Original Flower Remedies, Remedy®, Natural Stress Relief, 0.7 fl oz ", brand: "Bach Original Flower Remedies", category: "flower-essence", summary: "The emergency brake for acute panic, shock, or sudden rage spikes.", mechanism: "Rapidly interrupts the fight-or-flight cascade during acute nervous system flooding.", caution: "Contains alcohol; avoid if sensitive or in recovery." },
  { asin: "B07BR4QRT1", title: "Four Sigmatic Mushroom Coffee Mix Pack of 4 - Lion's Mane and Chaga", brand: "Four Sigmatic", category: "mushroom", summary: "A grounded alternative to jitter-inducing caffeine that keeps you sharp without the crash.", mechanism: "Pairs organic coffee with adaptogenic extracts to provide sustained energy and mental clarity.", caution: "Contains caffeine; avoid late in the day if you struggle with sleep." },
  { asin: "B0756D1D39", title: "Four Sigmatic Organic Focus Mushroom Ground Coffee | Dark Roast", brand: "Four Sigmatic", category: "mushroom", summary: "Dark roast coffee infused with functional mushrooms to cut through brain fog and anchor your morning.", mechanism: "Utilizes Lion's Mane and Chaga to support cognitive function while buffering the stress response.", caution: "Monitor your caffeine intake if you are prone to anxiety or palpitations." },
  { asin: "B001E0SYWG", title: "Mushroom Wisdom D Fraction Liq2", brand: "Mushroom Wisdom", category: "mushroom", summary: "A potent liquid extract of Maitake to deeply nourish and protect the physical vessel.", mechanism: "Concentrates the D-fraction of Maitake to strongly activate cellular immune defenses.", caution: "May lower blood sugar; monitor closely if you are diabetic or hypoglycemic." },
  { asin: "B000KHTT0A", title: "Maitake Products, Mushroom Wisdom Super Lion's Mane - 120 vcaps", brand: "Mushroom Wisdom", category: "mushroom", summary: "Targeted support for the brain and nervous system to help you stay present and embodied.", mechanism: "Combines Lion's Mane extract with Vitamin C to enhance absorption and neural repair.", caution: "Discontinue use if you experience any allergic reactions or skin rashes." },
  { asin: "B00B62YLNI", title: "Sun Potion Pearl Powder - Levigated Freshwater Pearl Supplement", brand: "Sun Potion", category: "mushroom", summary: "A mineral-rich tonic to cool an overheated system and soothe frayed nerves.", mechanism: "Provides bioavailable calcium and amino acids to calm the spirit and support tissue repair.", caution: "Not a mushroom, but an adaptogenic mineral; use sparingly as part of a broader protocol." },
  { asin: "B00GDINIZC", title: "Organic India Ashwagandha Powder - 1 Pound", brand: "Organic India", category: "vata-ayurveda", summary: "Pure, organic Ashwagandha root powder to build resilience and calm the wired-and-tired nervous system.", mechanism: "A pure adaptogen that modulates the HPA axis, reducing the physiological impact of chronic stress.", caution: "May cause mild gastrointestinal upset in sensitive individuals." },
  { asin: "B000Q418U6", title: "Banyan Botanicals Organic Tranquil Mind - 90 Tablets", brand: "Banyan Botanicals", category: "vata-ayurveda", summary: "A targeted blend to quiet a restless mind, ease physical tension, and support deep, restorative sleep.", mechanism: "Nervine herbs like Bhringaraj and Skullcap directly soothe the central nervous system and promote relaxation.", caution: "May cause drowsiness; use caution when driving or operating machinery." },
  { asin: "B0006NZPGA", title: "Himalaya Organic Bacopa Monnieri - 60 Caplets", brand: "Himalaya", category: "vata-ayurveda", summary: "A single-herb powerhouse for mental focus and emotional stability when Vata imbalance causes brain fog.", mechanism: "Bacopa monnieri supports neurotransmitter balance, enhancing cognitive resilience under stress.", caution: "May cause mild stomach upset if taken on an empty stomach." },
  { asin: "B000VDN1B6", title: "Organic India Tulsi Original Herbal Tea - 108 Count", brand: "Organic India", category: "vata-ayurveda", summary: "A soothing, grounding tea that calms the nervous system and provides a moment of physical stillness.", mechanism: "Holy Basil acts as a gentle adaptogen, lowering cortisol and supporting a balanced immune response.", caution: "Consult a practitioner if trying to conceive or currently pregnant." },
  { asin: "B0797DVMF3", title: "THORNE Stress B-Complex - 60 Capsules", brand: "Thorne", category: "vitamin-mineral", summary: "Targeted B-vitamin support for bodies running on fumes and chronic stress.", mechanism: "Delivers extra vitamin B5 alongside active B vitamins to support adrenal function and stress response.", caution: "Bright yellow urine is a normal, harmless side effect." },
  { asin: "B0016003Z0", title: "Jarrow Formulas B-Right - 100 Veggie Caps", brand: "Jarrow Formulas", category: "vitamin-mineral", summary: "A low-odor B-complex designed for efficient absorption and nervous system repair.", mechanism: "Supplies methylated B vitamins to support cellular energy and neurological health.", caution: "Contains niacin, which may cause a temporary, harmless flush." },
  { asin: "B0797GZDZL", title: "THORNE Iron Bisglycinate - 60 Capsules", brand: "Thorne", category: "vitamin-mineral", summary: "Gentle, non-constipating iron to rebuild physical stamina and oxygenate the blood.", mechanism: "Provides a highly absorbable form of iron to combat fatigue without gastrointestinal distress.", caution: "Accidental overdose of iron-containing products is a leading cause of fatal poisoning in children under 6." },
  { asin: "B000Z4ZQB4", title: "Vital Nutrients Lithium Orotate 5mg - 90 Capsules", brand: "Vital Nutrients", category: "vitamin-mineral", summary: "A micro-dose of elemental support for a frayed, reactive nervous system.", mechanism: "Provides low-dose lithium to support mood stability and cognitive function.", caution: "Not a replacement for prescription lithium; consult a doctor if bipolar." },
  { asin: "B0C62SZL3Q", title: "Double Wood Supplements Lithium Orotate 5mg - 120 Capsules", brand: "Double Wood Supplements", category: "vitamin-mineral", summary: "Gentle mineral support to help take the edge off chronic mental tension.", mechanism: "Delivers elemental lithium to promote a balanced state of mind and behavioral health.", caution: "Do not exceed recommended dose without medical supervision." },
  { asin: "B07P5K7DQP", title: "Pure Encapsulations Magnesium Glycinate, 90 Capsules", brand: "Pure Encapsulations", category: "magnesium", summary: "A highly bioavailable magnesium glycinate that absorbs cleanly without wrecking your gut.", mechanism: "Binds magnesium to glycine, calming the nervous system and easing muscle tension without the laxative effect.", caution: "Take with food if you have a sensitive stomach." },
  { asin: "B0797HBLL3", title: "THORNE Magnesium Bisglycinate Powder, 60 Servings", brand: "THORNE", category: "magnesium", summary: "A clean, powdered magnesium bisglycinate that mixes easily and hits the bloodstream fast.", mechanism: "Delivers magnesium directly to tissues to quiet the physical hum of anxiety and support deep rest.", caution: "Start with a half scoop to assess tolerance." },
  { asin: "B000BD0RT0", title: "Doctor's Best High Absorption Magnesium Glycinate, 240 Count", brand: "Doctor's Best", category: "magnesium", summary: "A reliable, chelated magnesium that gets the job done for tight muscles and restless nights.", mechanism: "Uses a chelated form to bypass digestive interference, directly relaxing clenched muscles and a wired brain.", caution: "Pills are large; take with plenty of water." },
  { asin: "B00BPUY3W0", title: "Natural Vitality Calm Magnesium Powder, Raspberry Lemon, 16oz", brand: "Natural Vitality", category: "magnesium", summary: "A fizzy, fast-acting magnesium citrate drink that forces a physical exhale.", mechanism: "Pulls water into the intestines while rapidly raising blood magnesium levels to blunt the stress response.", caution: "Will cause diarrhea if you take too much; start slow." },
  { asin: "B09WWK4R2C", title: "Momentous Magtein Magnesium L-Threonate, 30 Servings", brand: "Momentous", category: "magnesium", summary: "A specialized magnesium designed specifically to cross the blood-brain barrier and quiet the mind.", mechanism: "Elevates brain magnesium levels to support cognitive function and turn down the volume on racing thoughts.", caution: "Can cause mild headaches during the first few days of use." },
  { asin: "B07Q3T2N6Z", title: "Tattva's Herbs Ayurvedic Pitta Cooling Massage Oil 8oz", brand: "Tattva's Herbs", category: "pitta-ayurveda", summary: "A grounding, cooling oil to literally rub the heat out of your nervous system.", mechanism: "Transdermal absorption of cooling herbs pulls excess heat from the tissues and down-regulates a spiked nervous system.", caution: "External use only; avoid if you are already running cold or feeling lethargic." },
  { asin: "B0041V8F3S", title: "Organic India Brahmi Gotu Kola", brand: "Organic India", category: "pitta-ayurveda", summary: "A sharp, direct intervention for a mind that won't stop spinning and snapping.", mechanism: "Cools the central nervous system and clears mental heat, reducing the sharp, critical edge of pitta-driven anger.", caution: "May cause mild stomach upset if taken on an empty stomach." },
  { asin: "B000703AQ4", title: "Banyan Botanicals Organic Shatavari Tablets - 90 Tablets", brand: "Banyan Botanicals", category: "pitta-ayurveda", summary: "Deep, cooling nourishment for when you've burned yourself out with rage.", mechanism: "Replenishes depleted fluids and cools systemic heat, providing a physical buffer against stress and irritability.", caution: "Avoid if you have heavy congestion or excess mucus." },
  { asin: "B009TE7H5O", title: "Banyan Botanicals Neem & Aloe Soap - 4 oz Bar", brand: "Banyan Botanicals", category: "pitta-ayurveda", summary: "A literal cold shower for your skin when you're running hot and bothered.", mechanism: "Draws heat out through the skin using intensely cooling neem and aloe, lowering overall body temperature and agitation.", caution: "Can be drying; follow with a grounding oil if your skin feels tight." },
  { asin: "B001FAYUVO", title: "Banyan Botanicals Avipattikar Powder - 1/2 lb", brand: "Banyan Botanicals", category: "pitta-ayurveda", summary: "A fast-acting powder to extinguish the fire in your gut before it reaches your mouth.", mechanism: "Directly neutralizes excess stomach acid and clears heat from the digestive tract, cutting off anger at its physical root.", caution: "Do not use if you have active diarrhea or severe dehydration." },
  { asin: "B00GDXHBS2", title: "THORNE - 5-HTP - Contains Vitamin B6 - Serotonin Support - 90 Capsules", brand: "Thorne", category: "amino-acid", summary: "A direct precursor to serotonin that bypasses the body's usual bottlenecks to flood the system with raw calming material.", mechanism: "Converts directly into serotonin in the brain, short-circuiting the rage loop and forcing the nervous system to stand down.", caution: "Do not combine with SSRIs or other serotonin-altering medications without medical supervision." },
  { asin: "B00020IA6E", title: "Solgar Taurine 500 mg, 250 Vegetable Capsules - Antioxidant - Brain Health", brand: "Solgar", category: "amino-acid", summary: "A heavy-duty nervous system anchor that pulls you back into your body when the adrenaline spikes.", mechanism: "Acts as an inhibitory neurotransmitter, slamming the brakes on overexcited neurons and preventing the escalation of panic or rage.", caution: "May lower blood pressure; monitor if you are prone to hypotension." },
  { asin: "B00B0YA0K0", title: "NOW Foods - GABA with Vitamin B6 500 mg. - 200 Vegetarian Capsules", brand: "NOW Foods", category: "amino-acid", summary: "The brain's primary off-switch, delivered straight to the source to quiet the noise and stop the spiral.", mechanism: "Binds to GABA receptors to block stress signals, effectively muting the physiological response to anger triggers.", caution: "Can cause mild drowsiness; avoid driving until you know how it affects you." },
  { asin: "B0DZ42848R", title: "Premier Research Labs L-Theanine Double Strength - Pure L Theanine Supplement 200mg", brand: "Premier Research Labs", category: "amino-acid", summary: "A precision tool for focus and calm, cutting through the fog of anger without sedating the body.", mechanism: "Increases alpha brain waves, promoting a state of alert relaxation that neutralizes the fight-or-flight response.", caution: "Generally well-tolerated, but excessive doses may cause mild gastrointestinal upset." },
  { asin: "B08DTQ77BB", title: "THORNE - RecoveryPro - Whey Protein Powder with Magnesium, GABA & L-Tryptophan", brand: "Thorne", category: "amino-acid", summary: "A comprehensive nighttime reset button that rebuilds the nervous system while you sleep.", mechanism: "Combines key amino acids and minerals to force the body into deep recovery, lowering baseline tension for the next day.", caution: "Contains dairy; avoid if you have a severe milk allergy or lactose intolerance." },
  { asin: "B0010ZWJMQ", title: "Source Naturals Serene Science 5-HTP, Balanced Mood 100 mg - 30 Capsules", brand: "Source Naturals", category: "amino-acid", summary: "A concentrated dose of serotonin support to stabilize the mood and prevent the drop into rage.", mechanism: "Directly fuels the production of serotonin, stabilizing emotional volatility and reducing the intensity of anger spikes.", caution: "Do not use if taking MAOIs or other antidepressants." },

];

export const CATEGORY_LABEL: Record<Herb["category"], string> = {
  "nervous-system": "Nervines (Western Herbalism)",
  "liver-tcm": "TCM · Liver Channel",
  "pitta-ayurveda": "Ayurveda · Pitta",
  "vata-ayurveda": "Ayurveda · Vata",
  adaptogen: "Adaptogens",
  magnesium: "Magnesium",
  "amino-acid": "Amino Acids",
  aromatherapy: "Aromatherapy",
  mushroom: "Mushrooms",
  "vitamin-mineral": "Vitamins & Minerals",
  "flower-essence": "Flower Essences",
  "herbal-tea": "Herbal Teas",
};

// Sanity guard — refuse to ship an empty cabinet.
// Floor lowered after re-verifying against live Amazon and removing 38 more
// dead/unavailable listings on top of the previous 70 prune. Soft-warn at <80
// so the cabinet is replenished before it gets thin.
if (HERBS.length === 0) {
  throw new Error(`HERBS array is empty — cabinet cannot ship`);
}
if (HERBS.length < 80) {
  console.warn(`[herbs] only ${HERBS.length} entries; consider replenishing the cabinet`);
}
