// 30 seed topics from SCOPE-SITE-82. Longer 500-article queue lives in data/topics-queue.json
export const SEED_TOPICS: string[] = [
  "Why You Were Taught That Anger Is Wrong (And Why That's Destroying You)",
  "Anger Is a Boundary: What Your Rage Is Actually Protecting",
  "The Somatic Release of Anger: How to Get It Out of Your Body",
  "Suppressed Anger and Disease: What the Research Shows",
  "Women and Rage: Why Society Fears Female Anger",
  "The Difference Between Anger and Aggression (And Why It Matters)",
  "How to Be Angry Without Destroying Your Relationships",
  "Childhood Anger Suppression and Adult Health",
  "The Nervous System of Anger: What's Actually Happening",
  "Anger After Trauma: Why It Surfaces Years Later",
  "The Spiritual Bypassing of 'Just Let It Go'",
  "How to Feel Anger in Your Body: A Practice Guide",
  "Anger and Grief: The Connection Nobody Talks About",
  "The Pillow Scream, the Forest Howl, and Other Rage Practices",
  "Why 'Calm Down' Is the Worst Thing You Can Say",
  "TCM and Anger: Liver Qi Stagnation and Rising Fire",
  "The Anger Inventory: Naming Every Resentment You're Carrying",
  "How to Set Boundaries When You've Been People-Pleasing Your Whole Life",
  "Anger in Meditation: What Happens When Rage Surfaces on the Cushion",
  "The Freeze Response: When Anger Gets Stuck",
  "Passive-Aggressive Behavior as Suppressed Rage",
  "Teaching Children Healthy Anger: What You Never Learned",
  "Anger and the Workplace: Speaking Up Without Blowing Up",
  "The Physical Practice of Rage: Movement, Sound, and Breath",
  "Why Forgiveness Before Anger Is Spiritual Bypassing",
  "Anger Journaling: The Uncensored Page",
  "Ayurvedic Pitta and Anger: Cooling the Fire Without Extinguishing It",
  "The Anger-Shame Cycle: How They Feed Each Other",
  "How to Support a Partner Who Is Learning to Feel Anger",
  "Reclaiming Your Fire: When Anger Becomes Power",
];
